### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Larissa Andrade",
  "cpf": "11144477735",
  "genero": "F",
  "data_nascimento": "1990-05-15",
  "cargo": "Desenvolvedora",
  "senha": "Larissa@2025",
  "data_contratacao": "2024-07-01",
  "role": "usuario"
}

### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Rafael Monteiro",
  "cpf": "54294676000",
  "genero": "M",
  "data_nascimento": "1988-03-22",
  "cargo": "Analista de Dados",
  "senha": "Rafa@2025",
  "data_contratacao": "2024-08-15",
  "role": "usuario"
}


### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Juliana Costa",
  "cpf": "88997057049",
  "genero": "F",
  "data_nascimento": "1992-11-05",
  "cargo": "Gerente de Projetos",
  "senha": "JuCosta@123",
  "data_contratacao": "2023-11-20",
  "role": "usuario"
}


### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Carlos Henrique",
  "cpf": "60394609034",
  "genero": "M",
  "data_nascimento": "1985-07-19",
  "cargo": "Engenheiro de Software",
  "senha": "Carlos@Dev2024",
  "data_contratacao": "2025-01-05",
  "role": "usuario"
}


### Criar novo usuário - USUARIO ANTIGO
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Amanda Ribeiro",
  "cpf": "33383627063",
  "genero": "F",
  "data_nascimento": "1994-12-30",
  "cargo": "UX Designer",
  "senha": "Amanda@2024",
  "data_contratacao": "2024-04-10",
  "role": "usuario"
}

### Criar novo usuário - USUARIO NOVO
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Camila Rocha",
  "cpf": "31415926590",
  "genero": "F",
  "data_nascimento": "1994-07-07",
  "cargo": "Operadora",
  "senha": "CamilaR#2025",
  "data_contratacao": "2025-08-01",
  "role": "usuario",
  "email": "camila.rocha@example.com"
}



### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Eduardo Martins",
  "cpf": "55566677720",
  "genero": "M",
  "data_nascimento": "1986-01-11",
  "cargo": "Coordenador",
  "senha": "Eduardo!Coord25",
  "data_contratacao": "2025-06-01",
  "role": "usuario",
  "email": "eduardo.martins@example.com"
}


### DELETE USUARIO BY ID
DELETE http://localhost:8080/usuario/4