### Envio do Formulário de Manutenção Predial
POST http://localhost:8080/submit
Content-Type: application/json

{
  "formTitle": "Formulário de manutenção predial",
  "descricao": "Esse formulário tem o objetivo de verificar as condições do local afim de manter segurança, funcionalidade e conservação do ambiente de trabalho",
  "data_verificacao": "2025-10-20",
  "condicoes_piso_escritorio": "Bom estado, sem rachaduras",
  "condicoes_piso_operacional": "Algumas fissuras, necessita reparo",
  "condicoes_piso_galpao": "Piso limpo e nivelado",
  "condicoes_piso_refeitorio": "Limpo e sem obstruções",
  "condicoes_forro_escritorio": "Sem vazamentos",
  "condicoes_forro_operacional": "Algumas placas soltas",
  "condicoes_forro_galpao": "Em bom estado",
  "condicoes_forro_refeitorio": "Bom estado, limpo",
  "estado_geral_instalacoes_eletricas": "Todas as tomadas e fiações em bom estado",
  "estado_geral_protecao_raios": "Instalado e funcional",
  "carga_ar_condicionado_sala_adm": "SIM",
  "carga_ar_condicionado_sala_diretoria": "NÃO",
  "carga_ar_condicionado_sala_reuniao": "SIM",
  "carga_ar_condicionado_sala_operacional": "SIM",
  "lampadas_sala_adm": "SIM",
  "lampadas_sala_diretoria": "SIM",
  "lampadas_sala_reuniao": "SIM",
  "lampadas_sala_operacional": "SIM",
  "lampadas_galpao": "SIM",
  "lampadas_refeitorio": "SIM",
  "lampadas_banheiro_feminino": "NÃO",
  "lampadas_banheiro_masculino": "SIM",
  "macanetas_portas": "SIM",
  "mesas_operacional": "SIM",
  "condicoes_paleteiras_carrinho": "Paleteiras em bom estado, carrinho hidráulico com manutenção em dia",
  "organizacao_locais_trabalho": "Tudo organizado, sem risco para funcionários",
  "cameras_seguranca": "SIM",
  "condicoes_balanca_piso": "Em bom estado e calibrada",
  "data_ultima_afericao_balanca": "2025-09-15",
  "condicoes_mictorios_lavatorios": "Limpos e funcionais",
  "data_ultima_limpeza_bebedouro": "2025-10-01",
  "data_proxima_dedetizacao": "2026-01-20",
  "data_ultima_recarga_extintores": "2025-05-15",
  "data_proxima_recarga_extintores": "2026-05-15",
  "data_ultima_limpeza_caixa_dagua": "2025-06-10",
  "data_proxima_limpeza_caixa_dagua": "2026-06-10",
  "cadeira_ma_condicao": "SIM",
  "descricao_cadeira_ma_condicao": "Cadeira na sala operacional, posição central, assento rasgado",
  "detalhe_adicional": "Sala do galpão precisa de ventilação extra"
}
