### Criar super usuário
POST http://35.232.26.46:8080/usuario/create
Content-Type: application/json

{
  "nome": "Thiago Lima",
  "cpf": "85107366007",
  "genero": "M",
  "dataNascimento": "1985-04-20",
  "cargo": "Product Owner",
  "setor": "Desenvolvimento",
  "senha": "Thiago@PO2025",
  "dataContratacao": "2025-09-01",
  "role": "admin"
}



### login Adiministrador Thiago
# @name login
POST http://35.232.26.46:8080/login
Content-Type: application/json

{
  "cpf": "85107366007",
  "senha": "Thiago@PO2025"
}

### login Colaborador Larissa
# @name login
POST http://localhost:8080/login
Content-Type: application/json

{
  "cpf": "11144477735",
  "senha": "Larissa@2025"
}

###
@token = {{login.response.body.token}}

### logout
POST http://localhost:8080/logout
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### Listar todos os usuários (requer admin)
GET http://localhost:8080/usuario/list
Authorization: Bearer {{token}}
Content-Type: application/json 

{}

### Listar usuário por ID (requer ou seja o mesmo usuário ou admin)
GET http://localhost:8080/usuario/1
Authorization: Bearer {{token}}
Content-Type: application/json 

{}

### Atualizar usuário (requer admin)
PUT http://localhost:8080/usuario/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nome": "Larissa Andrade",
  "cpf": "11144477735",
  "genero": "F",
  "dataNascimento": "1990-05-15",
  "cargo": "Desenvolvedora",
  "senha": "Larissa@2025",
  "dataContratacao": "2024-07-01",
  "role": "admin"
}

### Deletar usuário (requer admin)
DELETE http://localhost:8080/usuario/6
Authorization: Bearer {{token}}
Content-Type: application/json 

{}


### Adicionar ou atualizar local de trabalho de um usuário
POST http://localhost:8080/usuario/2/local
Content-Type: application/json

{
  "local": "REMOTO"
}


### Checar se o modal deve aparecer, se o usuario ja preencheu a coluna de local de trabalho hoje
GET http://localhost:8080/usuario/2/local/check
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST http://35.232.26.46:8080/login