### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Larissa Andrade",
  "cpf": "111.444.777-35",
  "email": "larissa.andrade@email.com",
  "telefone": "11987654321",
  "cargo": "Desenvolvedora",
  "senha": "Larissa@2025",
  "data_contratacao": "2024-07-01"
}

### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Rafael Monteiro",
  "cpf": "542.946.760-00",
  "email": "rafael.monteiro@email.com",
  "telefone": "21999887766",
  "cargo": "Analista de Dados",
  "senha": "Rafa@2025",
  "data_contratacao": "2024-08-15"
}
### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Juliana Costa",
  "cpf": "889.970.570-49",
  "email": "juliana.costa@email.com",
  "telefone": "11912345678",
  "cargo": "Gerente de Projetos",
  "senha": "JuCosta@123",
  "data_contratacao": "2023-11-20"
}
### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Carlos Henrique",
  "cpf": "603.946.090-34",
  "email": "carlos.henrique@email.com",
  "telefone": "31998765432",
  "cargo": "Engenheiro de Software",
  "senha": "Carlos@Dev2024",
  "data_contratacao": "2025-01-05"
}
### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Amanda Ribeiro",
  "cpf": "333.836.270-63",
  "email": "amanda.ribeiro@email.com",
  "telefone": "21987654321",
  "cargo": "UX Designer",
  "senha": "Amanda@2024",
  "data_contratacao": "2024-04-10"
}