### Criar novo usuário
POST http://localhost:8080/user
Content-Type: application/json

{
  "nome": "Gustavo",
  "cpf": "54297676001",
  "email": "larissa44o.andrade@email.com",
  "senha": "12346"
}


### Criar login
POST http://localhost:8080/login
Content-Type: application/json

{
  "cpf": "54297676001",
  "senha": "12346"
}

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVJ9.eyJpZCI6NCwiY3BmIjoiNTQyOTc2NzYwMDEiLCJpYXQiOjE3NTgyODg5NDAsImV4cCI6MTc1ODI5MjU0MH0.eVXtXzsVEzli2TF2iBlkVDlU5jURY1d3xwLuBInxwjA

### logout
POST http://localhost:8080/logout
Authorization: {{token}}
Content-Type: application/json

{
 
}
### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Carlos Henrique",
  "cpf": "603.946.090-34",
  "email": "carlos.henrique@email.com",
  "telefone": "31998765432",
  "cargo": "Engenheiro de Software",
  "senha": "Carlos@Dev2024",
  "data_contratacao": "2025-01-05"
}
### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Amanda Ribeiro",
  "cpf": "333.836.270-63",
  "email": "amanda.ribeiro@email.com",
  "telefone": "21987654321",
  "cargo": "UX Designer",
  "senha": "Amanda@2024",
  "data_contratacao": "2024-04-10"
}
### Criar novo usuário
POST http://localhost:8080/usuario/create
Content-Type: application/json

{
  "nome": "Thiago Lima",
  "cpf": "851.073.660-07",
  "email": "thiago.lima@email.com",
  "telefone": "11999988877",
  "cargo": "Product Owner",
  "senha": "Thiago@PO2025",
  "data_contratacao": "2025-09-01"
}

### Listar todos os usuários
GET http://localhost:8080/usuario/list

### Listar usuário específico por ID
GET http://localhost:8080/usuario/6

### Atualizar usuário por ID
PUT http://localhost:8080/usuario/6
Content-Type: application/json

{
  "nome": "Thiago Lima",
  "cpf": "851.073.660-07",
  "email": "thiago.lima@email.com",
  "telefone": "11999988877",
  "cargo": "Product Owner",
  "senha": "Thiago@PO2025",
  "data_contratacao": "2025-09-01"
}

### Deletar usuário por ID
DELETE http://localhost:8080/usuario/6